runtime: java11
env: standard
service: testservice
instance_class: F2
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "staging"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1